# Generated by Django 4.2.7 on 2023-11-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('last_login_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('usage_json', models.JSONField(null=True)),
                ('useraccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.useraccount')),
            ],
        ),
    ]
