# Generated by Django 4.2.7 on 2023-11-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeusage',
            name='first_entry',
            field=models.BooleanField(default=True),
        ),
    ]
