# Generated by Django 4.2.7 on 2023-11-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_timeusage_first_entry_timeusage_previous_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeusage',
            name='previous_app',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='timeusage',
            name='previous_url',
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
