# Generated by Django 5.0.1 on 2024-01-10 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_timeusage_previous_app_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="last_login_date",
        ),
    ]
