# Generated by Django 5.0.1 on 2024-02-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_remove_useraccount_last_login_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="password",
        ),
        migrations.AlterField(
            model_name="timeusage",
            name="previous_app",
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name="timeusage",
            name="previous_url",
            field=models.CharField(blank=True, default=None, max_length=2000),
        ),
    ]
