# Generated by Django 5.0.1 on 2024-02-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_remove_useraccount_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeusage",
            name="previous_app",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="timeusage",
            name="previous_url",
            field=models.CharField(default=None, max_length=2000, null=True),
        ),
    ]
